### ISSUE TITLE
Still a little confused about this project's aim

### ISSUE THREAD

**Issue by gcz2022** [adrian-wang/spark-package-maker#2]
Could you illustrate more or give an example?

**Comment by gcz2022** [comment]
For exmaple, for OAP, can't it all be done through maven?

**Comment by adrian-wang** [comment]
Before, OAP code and Apache spark code are mixed in one repo, this project provide a script to separate OAP code from Spark repo.

**Comment by gcz2022** [comment]
：）Thanks. Looking forward to this
